
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/jello/Scrolls/clion-2024.3.2/bin/cmake/linux/x64/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.13.2-arch1-1 - x86_64
...
